-- V10__notification_settings.sql
-- roadmap 007 §1 notification_settings (one row per senior).
-- GET returns defaults (enabled/5/3) when no row exists; PUT upserts (primary caregiver only).

CREATE TABLE notification_settings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    senior_id           BIGINT NOT NULL UNIQUE REFERENCES users (id),
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    remind_interval_min INT NOT NULL DEFAULT 5 CHECK (remind_interval_min > 0),
    max_retries         INT NOT NULL DEFAULT 3 CHECK (max_retries >= 0),
    updated_by          BIGINT NULL REFERENCES users (id),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
