-- V12__notifications.sql
-- WP3a channel-independent reminder/escalation engine (in-app notifications).
-- type/level CHECK enums match the UPPERCASE Kotlin enum. Delivery channels
-- (web push / SMS) are a SEPARATE later task (WP3b) and are NOT modelled here.
-- The UNIQUE (dose_event_id, type, level) guard makes escalation generation
-- idempotent: re-running the evaluator never inserts a duplicate rung.

CREATE TABLE notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_group_id BIGINT NOT NULL REFERENCES care_groups (id),
    senior_id     BIGINT NOT NULL REFERENCES users (id),
    dose_event_id BIGINT NULL REFERENCES dose_events (id),
    type          VARCHAR(20) NOT NULL
                    CHECK (type IN ('REMINDER', 'MISSED', 'ESCALATION')),
    level         INT NOT NULL DEFAULT 0,
    title         VARCHAR(120) NOT NULL,
    body          VARCHAR(300) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at       TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT ux_notifications_event_type_level UNIQUE (dose_event_id, type, level)
);

CREATE INDEX ix_notifications_group_created ON notifications (care_group_id, created_at DESC);
CREATE INDEX ix_notifications_senior_created ON notifications (senior_id, created_at DESC);
