CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_type   VARCHAR(20) NOT NULL CHECK (user_type IN ('SENIOR', 'CAREGIVER', 'PHARMACIST')),
    name        VARCHAR(100) NOT NULL,
    phone       VARCHAR(30) NOT NULL UNIQUE,
    birth_date  DATE NULL,
    pharmacy_id BIGINT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE care_groups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    senior_id  BIGINT NOT NULL REFERENCES users (id),
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ux_care_groups_senior_id ON care_groups (senior_id);

CREATE TABLE care_group_members (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_group_id  BIGINT NOT NULL REFERENCES care_groups (id),
    user_id        BIGINT NOT NULL REFERENCES users (id),
    role           VARCHAR(30) NOT NULL CHECK (role IN ('OWNER', 'FAMILY', 'SOCIAL_WORKER')),
    status         VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'PENDING', 'REMOVED')),
    invited_by     BIGINT NULL REFERENCES users (id),
    joined_at      TIMESTAMP WITH TIME ZONE NULL
);

CREATE UNIQUE INDEX ux_care_group_members_group_user ON care_group_members (care_group_id, user_id);
CREATE INDEX ix_care_group_members_group ON care_group_members (care_group_id);

CREATE TABLE invite_links (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_group_id BIGINT NOT NULL REFERENCES care_groups (id),
    token         VARCHAR(100) NOT NULL UNIQUE,
    expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    max_uses      INTEGER NULL CHECK (max_uses IS NULL OR max_uses > 0),
    use_count     INTEGER NOT NULL DEFAULT 0 CHECK (use_count >= 0),
    created_by    BIGINT NOT NULL REFERENCES users (id),
    revoked_at    TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX ix_invite_links_group ON invite_links (care_group_id);
