CREATE TABLE pharmacies (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    phone   VARCHAR(30) NOT NULL,
    address VARCHAR(255) NULL
);

CREATE UNIQUE INDEX ux_pharmacies_name_phone ON pharmacies (name, phone);

ALTER TABLE users
    ADD CONSTRAINT fk_users_pharmacy
    FOREIGN KEY (pharmacy_id)
    REFERENCES pharmacies (id);

CREATE TABLE prescriptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    senior_id       BIGINT NOT NULL REFERENCES users (id),
    pharmacy_id     BIGINT NOT NULL REFERENCES pharmacies (id),
    registered_by   BIGINT NULL REFERENCES users (id),
    prescribed_date DATE NOT NULL,
    start_date      DATE NOT NULL,
    end_date        DATE NULL,
    status          VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'ENDED')),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_prescriptions_senior_status ON prescriptions (senior_id, status);
CREATE INDEX ix_prescriptions_pharmacy ON prescriptions (pharmacy_id);

CREATE TABLE medications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    category    VARCHAR(100) NULL,
    photo_url   VARCHAR(500) NULL,
    description VARCHAR(500) NULL
);

CREATE INDEX ix_medications_name_category ON medications (name, category);

CREATE TABLE dose_schedules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id BIGINT NOT NULL REFERENCES prescriptions (id),
    slot            VARCHAR(20) NOT NULL CHECK (slot IN ('MORNING', 'LUNCH', 'DINNER', 'BEDTIME', 'CUSTOM')),
    label           VARCHAR(100) NOT NULL,
    packet_no       INTEGER NULL CHECK (packet_no IS NULL OR packet_no > 0),
    scheduled_time  TIME NOT NULL,
    meal_relation   VARCHAR(20) NOT NULL CHECK (meal_relation IN ('BEFORE_MEAL', 'AFTER_MEAL', 'WITH_MEAL', 'NONE')),
    meal_offset_min INTEGER NULL CHECK (meal_offset_min IS NULL OR meal_offset_min >= 0),
    pill_count      INTEGER NULL CHECK (pill_count IS NULL OR pill_count > 0),
    active          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX ix_dose_schedules_prescription ON dose_schedules (prescription_id);
CREATE INDEX ix_dose_schedules_time ON dose_schedules (scheduled_time);

CREATE TABLE dose_schedule_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dose_schedule_id BIGINT NOT NULL REFERENCES dose_schedules (id),
    medication_id    BIGINT NOT NULL REFERENCES medications (id),
    count            INTEGER NOT NULL CHECK (count > 0)
);

CREATE UNIQUE INDEX ux_dose_schedule_items_schedule_medication
    ON dose_schedule_items (dose_schedule_id, medication_id);
