CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_type   VARCHAR(20) NOT NULL CHECK (user_type IN ('SENIOR', 'CAREGIVER', 'PHARMACIST')),
    name        VARCHAR(100) NOT NULL,
    phone       VARCHAR(30) NOT NULL UNIQUE,
    birth_date  DATE NULL,
    pharmacy_id BIGINT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS care_groups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    senior_id  BIGINT NOT NULL REFERENCES users (id),
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_care_groups_senior_id ON care_groups (senior_id);

CREATE TABLE IF NOT EXISTS care_group_members (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_group_id  BIGINT NOT NULL REFERENCES care_groups (id),
    user_id        BIGINT NOT NULL REFERENCES users (id),
    role           VARCHAR(30) NOT NULL CHECK (role IN ('OWNER', 'FAMILY', 'SOCIAL_WORKER')),
    status         VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'PENDING', 'REMOVED')),
    invited_by     BIGINT NULL REFERENCES users (id),
    joined_at      TIMESTAMP WITH TIME ZONE NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_care_group_members_group_user ON care_group_members (care_group_id, user_id);
CREATE INDEX IF NOT EXISTS ix_care_group_members_group ON care_group_members (care_group_id);
CREATE INDEX IF NOT EXISTS ix_care_group_members_user ON care_group_members (user_id);

CREATE TABLE tts_clips (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text_hash   VARCHAR(64) NOT NULL,
    voice       VARCHAR(80) NOT NULL,
    text        TEXT NOT NULL,
    object_key  VARCHAR(500) NOT NULL,
    duration_ms INTEGER NOT NULL CHECK (duration_ms >= 0),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_tts_clips_voice_text_hash UNIQUE (voice, text_hash)
);

CREATE TABLE images (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type   VARCHAR(40) NOT NULL CHECK (owner_type IN ('CARE_GROUP', 'MEDICATION', 'DOSE_EVENT')),
    owner_id     BIGINT NOT NULL,
    object_key   VARCHAR(500) NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    size_bytes   INTEGER NOT NULL CHECK (size_bytes > 0),
    uploaded_by  BIGINT NOT NULL REFERENCES users (id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_images_owner ON images (owner_type, owner_id);
CREATE INDEX ix_images_uploaded_by ON images (uploaded_by);
