-- V6__dose_events.sql
-- Per-day dose instances + confirmation log. media=V5, this=V6.
-- status/confirm_method CHECK enums match the UPPERCASE Kotlin enums.
-- Unique (dose_schedule_id, scheduled_date) makes the lazy generator idempotent.

CREATE TABLE dose_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dose_schedule_id BIGINT NOT NULL REFERENCES dose_schedules (id),
    senior_id        BIGINT NOT NULL REFERENCES users (id),
    scheduled_date   DATE NOT NULL,
    scheduled_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED'
                        CHECK (status IN ('SCHEDULED', 'TAKEN', 'MISSED', 'SKIPPED')),
    confirmed_at     TIMESTAMP WITH TIME ZONE NULL,
    confirm_method   VARCHAR(20) NULL
                        CHECK (confirm_method IS NULL OR confirm_method IN ('VOICE', 'BUTTON', 'CAREGIVER', 'AUTO')),
    confirmed_by     BIGINT NULL REFERENCES users (id),
    photo_image_id   BIGINT NULL REFERENCES images (id),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_dose_events_schedule_date UNIQUE (dose_schedule_id, scheduled_date),
    CONSTRAINT ck_dose_events_confirmed CHECK (
        (status = 'TAKEN') = (confirmed_at IS NOT NULL)
    )
);

CREATE INDEX ix_dose_events_senior_date ON dose_events (senior_id, scheduled_date);
CREATE INDEX ix_dose_events_schedule ON dose_events (dose_schedule_id);
CREATE INDEX ix_dose_events_photo ON dose_events (photo_image_id);
