-- V9__meal_times_and_change_log.sql
-- spec 005 §D meal_times (one row per senior) + §E change_log (generic audit).
-- Meal-derived alarm labels are computed lazily by the BFF; dose_events.scheduled_at
-- is NOT rewritten on meal-time change (documented follow-up).

CREATE TABLE meal_times (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    senior_id      BIGINT NOT NULL REFERENCES users (id),
    breakfast_time TIME NOT NULL,
    lunch_time     TIME NOT NULL,
    dinner_time    TIME NOT NULL,
    updated_by     BIGINT NULL REFERENCES users (id),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ux_meal_times_senior_id ON meal_times (senior_id);

CREATE TABLE change_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_group_id  BIGINT NOT NULL REFERENCES care_groups (id),
    actor_user_id  BIGINT NOT NULL REFERENCES users (id),
    target_type    VARCHAR(40) NOT NULL CHECK (target_type IN ('MEAL_TIME', 'MEMBER', 'PRESCRIPTION')),
    target_id      BIGINT NULL,
    field          VARCHAR(60) NOT NULL,
    old_value      VARCHAR(255) NULL,
    new_value      VARCHAR(255) NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_change_log_group_created ON change_log (care_group_id, created_at DESC);
